packages:
  - 02.todo
  - 03.weather
  - 04.marvel
  - 05.mealplanner
  - 06.fitness
  - 07.expenses
  - 08.quiz
  - 09.tensorflow
  - 10.portfolio

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - electron
  - esbuild
  - pngquant-bin
  - sharp
  - vue-demi

overrides:
  cross-spawn@<6.0.6: '>=6.0.6'
  file-type@>=13.0.0 <21.3.1: '>=21.3.1'
  got@<11.8.5: '>=11.8.5'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  phin@<3.7.1: '>=3.7.1'
  semver-regex@<3.1.3: '>=3.1.3'
  semver-regex@<3.1.4: '>=3.1.4'
